### ISSUE TITLE
Where are the data dictionary files used in the deploy.py file?

### ISSUE THREAD

**Issue by nihal-amat** [microsoft/dstoolkit-text2sql-and-imageprocessing#85]
I can see that there is a schema in the (https://github.com/microsoft/dstoolkit-text2sql-and-imageprocessing/blob/main/deploy_ai_search/src/deploy_ai_search/text_2_sql_schema_store.py), but I don't see where the Generated samples are being passed, could you please clarify?

**Comment by BenConstable9** [comment]
Hello @nihal-amat,

You need to upload these files to a storage account that the AI Search Indexer will pick them up from. I will update the documentation here on this.

**Comment by nihal-amat** [comment]
If my indexer is not working, can I manually push the JSON files from local to the index in the specified format?

**Comment by BenConstable9** [comment]
If you can format them into the specified format the the index expects, then yes and if you generate the embedding locally. 

You need to create some extra properties in the JSON, such as the ColumnDefinitions, combined column.
